s=set()
n=int(input("enter the nuber"))
s.add(n)
n=int(input("enter the nuber"))
s.add(n)
n=int(input("enter the nuber"))
s.add(n)
n=int(input("enter the nuber"))
s.add(n)
n=int(input("enter the nuber"))
s.add(n)
n=int(input("enter the nuber"))
s.add(n)
n=int(input("enter the nuber"))
s.add(n)
print (s)
